### ISSUE TITLE
node-telegram-bot-api should take advantage of chat_member in order to accomodate for new members in groups larger than 10k 

### ISSUE THREAD

**Issue by eduardstal** [james58899/TG-reCAPTCHA#7]
`new_chat_members` will not work on groups larger than 10k members, therefore chat members should be used instead

eg: https://github.com/yagop/node-telegram-bot-api/issues/923#issuecomment-996038501

https://www.npmjs.com/package/node-telegram-bot-api

**Comment by james58899** [comment]
It should fixed by https://github.com/james58899/TG-reCAPTCHA/commit/74e48ff5368113696bc04595f9ded907c8e5c451 .
